import type { Metadata } from "next";
import { Cormorant_Garamond, Montserrat } from "next/font/google";
import LenisProvider from "@/components/ui/LenisProvider";
import "./globals.css";

const cormorant_garmond = Cormorant_Garamond({
  variable: "--font-primary",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-secondary",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${cormorant_garmond.variable} ${montserrat.variable} antialiased`}
      >
        <LenisProvider />
        {children}
       
      </body>
    </html>
  );
}
